<?php

namespace OroAcademic\Bundle\SimpleBTSBundle\Entity\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use OroAcademic\Bundle\SimpleBTSBundle\Entity\Issue;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository
{
    /**
     * @var EntityManager
     */
    protected $entityManager;

    /**
     * @param EntityManager $entityManager
     */
    public function __construct(EntityManager $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    private function getEntityManager()
    {
        return $this->entityManager;
    }

    /**
     * @param Issue $issue
     * @return bool
     */
    public function update(Issue $issue)
    {
        if (!empty($issue)) {
            if (empty($issue->getCode())) {
                $issue->setCode($issue->getOrganization()->getName() . '-' . $issue->getId());
            }
            $entityManager = $this->getEntityManager();
            $entityManager->persist($issue);
            $entityManager->flush();

            return true;
        }

        return false;
    }
}
