<?php

namespace OroAcademic\Bundle\SimpleBTSBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use OroAcademic\Bundle\SimpleBTSBundle\Entity\Issue;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends EntityRepository
{
    /**
     * @param Issue $issue
     * @return bool
     */
    public function update(Issue $issue)
    {
        if (!empty($issue)) {
            if (empty($issue->getCode())) {
                $issue->setCode($issue->getOrganization()->getName() . '-' . $issue->getId());
            }
            $entityManager = $this->getEntityManager();
            $entityManager->persist($issue);
            $entityManager->flush();

            return true;
        }

        return false;
    }

    /**
     * @param Issue $issue
     * @return bool
     */
    public function delete(Issue $issue)
    {
        if (!empty($issue)) {
            $entityManager = $this->getEntityManager();
            $entityManager->remove($issue);
            $entityManager->flush();

            return true;
        }

        return false;
    }
}
