workflows:
    simple_bts_issue_workflow:
        attributes:
            resolution:
                label: oroacademic.simplebts.issue.resolution.label
                property_path: issue.resolution