imports:
    - { resource: 'issue_workflow/steps.yml' }
    - { resource: 'issue_workflow/attributes.yml' }
    - { resource: 'issue_workflow/transitions.yml' }
    - { resource: 'issue_workflow/transition_definitions.yml' }

workflows:
    simple_bts_issue_workflow:
        label: 'Issue Workflow'
        entity: Oro\Bundle\SimpleBTSBundle\Entity\Issue
        entity_attribute: status
        is_system: false
        start_step: open
        steps_display_ordered: true
