datagrid:
    oro_academic_sbts_issue_datagrid:
        #scope: oro_academic_sbts
        entity_class: '%oro_academic_sbts.entity.issue.class%'
        source:
            type: orm
            acl_resource: oro_academic_sbts_issue_view
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.summary
                    - issue.type
                    - priority.label as priorityLabel
                    - workflowStep.label as workflowStepLabel
                    - resolution.label as resolutionLabel
                    - reporter.id as reporterId
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - assignee.id as assigneeId
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as assigneeName
                    - issue.createdAt
                    - issue.updatedAt
                    - COUNT(DISTINCT subtask.id) as subtasksCount
                from:
                    - { table: '%oro_academic_sbts.entity.issue.class%', alias: issue }
                join:
                    left:
                        - { join: issue.priority, alias: priority }
                        - { join: issue.resolution, alias: resolution }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.assignee, alias: assignee }
                        - { join: issue.workflowStep, alias: workflowStep }
                        - { join: issue.children, alias: subtask }
                groupBy: issue.id
        columns:
            code:
                label:         oroacademic.simplebts.issue.code.label
            summary:
                label:         oroacademic.simplebts.issue.summary.label
            type:
                type:          twig
                label:         oroacademic.simplebts.issue.type.label
                frontend_type: html
                template:      OroAcademicSimpleBTSBundle:Issue:Datagrid/Property/type.html.twig
            priorityLabel:
                label:         oroacademic.simplebts.issue.priority.label
            workflowStepLabel:
                label:         oroacademic.simplebts.issue.workflow_status.label
            resolutionLabel:
                label:         oroacademic.simplebts.issue.resolution.label
            reporterName:
                type:          twig
                label:         oroacademic.simplebts.issue.reporter.label
                frontend_type: html
                template:      OroAcademicSimpleBTSBundle:Issue:Datagrid/Property/reporter.html.twig
            assigneeName:
                type:          twig
                label:         oroacademic.simplebts.issue.assignee.label
                frontend_type: html
                template:      OroAcademicSimpleBTSBundle:Issue:Datagrid/Property/assignee.html.twig
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
            subtasksCount:
                renderable:    false
        sorters:
            columns:
                code:
                    data_name: issue.code
                summary:
                    data_name: issue.summary
                type:
                    data_name: issue.type
                priorityLabel:
                    data_name: priority.priorityOrder
                workflowStepLabel:
                    data_name: workflowStep.stepOrder
                resolutionLabel:
                    data_name: resolution.name
                reporterName:
                    data_name: reporterName
                assigneeName:
                    data_name: assigneeName
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type:      string
                    data_name: issue.code
                summary:
                    type:      string
                    data_name: issue.summary
                type:
                    type:      string
                    data_name: issue.type
                priorityLabel:
                    type:      entity
                    data_name: priority.name
                    options:
                        field_options:
                            class: '%oro_academic_sbts.entity.issue.priority.class%'
                            property: label
                workflowStepLabel:
                    type:      entity
                    data_name: issue.workflowStep
                    options:
                        field_type: oro_workflow_step_select
                        field_options:
                            workflow_entity_class: '%oro_academic_sbts.entity.issue.class%'
                resolutionLabel:
                    type:      entity
                    data_name: resolution.name
                    options:
                        field_options:
                            class: '%oro_academic_sbts.entity.issue.resolution.class%'
                            property: label
                reporterName:
                    type:      string
                    data_name: reporterName
                assigneeName:
                    type:      string
                    data_name: assigneeName
                createdAt:
                    type:      datetime
                    data_name: issue.createdAt
                updatedAt:
                    type:      datetime
                    data_name: issue.updatedAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_academic_sbts_issue_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_academic_sbts_issue_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_academic_sbts_issue_delete_api
                params:     [ id ]
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
                acl_resource:  oro_academic_sbts_issue_view
            update:
                type:          navigate
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
                acl_resource:  oro_academic_sbts_issue_view
            delete:
                type:          delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
                acl_resource:  oro_academic_sbts_issue_view
        options:
            entity_pagination: true


    oro_academic_sbts_issue_subtask_datagrid:
        extends: oro_academic_sbts_issue_datagrid
        source:
            query:
                where:
                    and:
                        - issue.parent = :issueId
            bind_parameters:
                - issueId


    oro_academic_sbts_issue_collaborators_datagrid:
        source:
            type: orm
            acl_resource: oro_academic_sbts_issue_view
            query:
                select:
                    - collaborators.id
                    - CONCAT(collaborators.firstName, CONCAT(' ', collaborators.lastName)) as collaboratorFullName
                from:
                    - { table: '%oro_academic_sbts.entity.issue.class%', alias: issue }
                join:
                    inner:
                        - { join: issue.collaborators , alias: collaborators }
                where:
                    and:
                        - issue.id = :issueId
            bind_parameters:
                - issueId
        columns:
            collaboratorFullName:
                label: oroacademic.simplebts.issue.collaborators.label
            tags:
                renderable: false
            workflowStep:
                renderable: false
        sorters:
            columns:
                collaboratorFullName:
                    data_name: collaboratorFullName
            default:
                collaboratorFullName: ASC
        filters: ~
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_user_view
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_user_user_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true

    oro_academic_sbts_active_issue_datagrid:
        extends: oro_academic_sbts_issue_datagrid
        source:
            query:
                join:
                    left:
                        - { join: issue.collaborators, alias: collaborator }
                where:
                    and:
                        - collaborator.id = @oro_security.security_facade->getLoggedUserId
        columns:
            typeLabel:
                renderable:    false
            resolutionLabel:
                renderable:    false
            reporterName:
                renderable:    false
            tags:
                renderable:    false
            createdAt:
                renderable:    false
        filters: ~
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10

    oro_academic_sbts_active_issue_full_datagrid:
        extends: oro_academic_sbts_issue_datagrid
        source:
            query:
                join:
                    left:
                        - { join: issue.collaborators, alias: collaborator }
                where:
                    and:
                        - collaborator.id = @oro_security.security_facade->getLoggedUserId
        columns:
            typeLabel:
                renderable:    false
            resolutionLabel:
                renderable:    false
            reporterName:
                renderable:    false
            tags:
                renderable:    false
            createdAt:
                renderable:    false
        filters: ~
        options:
            toolbarOptions:
                hide: true

    oro_academic_sbts_user_issues_datagrid:
        extends: oro_academic_sbts_issue_datagrid
        source:
            query:
                where:
                    or:
                        - issue.assignee = :userId
                        - issue.reporter = :userId
            bind_parameters:
                - userId
        filters: ~
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10

    oro_academic_sbts_related_issues_grid_datagrid:
        source:
            type: orm
            acl_resource: oro_academic_sbts_issue_view
            query:
                select:
                    - issue.id
                    - relatedIssue.id AS linkedId
                    - relatedIssue.code
                    - relatedIssue.summary
                    - relatedIssue.type
                    - relatedIssuePriority.label as priorityLabel
                    - relatedIssueWorkflowStep.label as workflowStepLabel
                from:
                    - { table: '%oro_academic_sbts.entity.issue.class%', alias: issue }
                join:
                    inner:
                        - { join: issue.relatedIssues, alias: relatedIssue }
                    left:
                        - { join: relatedIssue.priority, alias: relatedIssuePriority }
                        - { join: relatedIssue.workflowStep, alias: relatedIssueWorkflowStep }
                where:
                    and:
                        - issue.id = :issueId
                orderBy:
                    - column: relatedIssue.id
                      dir: asc
            bind_parameters:
                - issueId
        columns:
            code:
                label:         oroacademic.simplebts.issue.code.label
            summary:
                label:         oroacademic.simplebts.issue.summary.label
            typeLabel:
                label:         oroacademic.simplebts.issue.type.label
            priorityLabel:
                label:         oroacademic.simplebts.issue.priority.label
            workflowStepLabel:
                label:         oroacademic.simplebts.issue.workflow_step.label
        properties:
            id: ~
            linkedId: ~
            view_link:
                type:       url
                route:      oro_academic_sbts_issue_view
                params:     [ id ]
            unlink_link:
                type:       url
                route:      oro_academic_sbts_issue_unlink
                params:
                     - linkedId
                     - id
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                rowAction:     true
                icon:          eye-open
                acl_resource:  oro_academic_sbts_issue_view
            unlink:
                type:          unlink
                label:         oroacademic.simplebts.issue.button.unlink
                link:          unlink_link
                icon:          eraser
                acl_resource:  oro_academic_sbts_issue_create
