parameters:
    oro_academic_sbts.form.type.issue.class:           OroAcademic\Bundle\SimpleBTSBundle\Form\Type\IssueType
    oro_academic_sbts.form.type.issue.api.class:       OroAcademic\Bundle\SimpleBTSBundle\Form\Type\IssueApiType
    oro_academic_sbts.form.handler.issue.class:        OroAcademic\Bundle\SimpleBTSBundle\Form\Handler\IssueHandler
    oro_academic_sbts.form.type.link_issue.class:      OroAcademic\Bundle\SimpleBTSBundle\Form\Type\LinkIssueType
    oro_academic_sbts.form.handler.link_issue.class:   OroAcademic\Bundle\SimpleBTSBundle\Form\Handler\LinkIssueHandler
    oro_academic_sbts.form.type.select_issue.class:    OroAcademic\Bundle\SimpleBTSBundle\Form\Type\IssueSelectType
    oro_academic_sbts.issue.manager.api.class:         Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    symfony.form.class:                                Symfony\Component\Form\Form

services:
    oro_academic_sbts.form.type.issue:
        class: '%oro_academic_sbts.form.type.issue.class%'
        tags:
            - { name: form.type, alias: oro_academic_sbts_issue }

    oro_academic_sbts.form.type.issue.api:
        class: '%oro_academic_sbts.form.type.issue.api.class%'
        tags:
            - { name: form.type, alias: oro_academic_sbts_issue_api }

    oro_academic_sbts.form.issue:
        class: '%symfony.form.class%'
        factory: ["@form.factory", createNamed]
        arguments:
            - oro_academic_sbts_issue_form
            - oro_academic_sbts_issue

    oro_academic_sbts.form.handler.issue:
        class: '%oro_academic_sbts.form.handler.issue.class%'
        scope: request
        arguments:
            - '@oro_academic_sbts.form.issue'
            - '@request'
            - '@doctrine.orm.entity_manager'
            - '@oro_entity.routing_helper'
        tags:
            - { name: oro_tag.tag_manager }

    # Issue API
    oro_academic_sbts.form.issue.api:
        class: '%symfony.form.class%'
        factory: ["@form.factory", createNamed]
        arguments:
            - ~
            - oro_academic_sbts_issue_api

    oro_academic_sbts.issue.manager.api:
        class: '%oro_academic_sbts.issue.manager.api.class%'
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - '%oro_academic_sbts.entity.issue.class%'
            - '@doctrine.orm.entity_manager'

    oro_academic_sbts.form.handler.issue.api:
        class: '%oro_academic_sbts.form.handler.issue.class%'
        scope: request
        arguments:
            - '@oro_academic_sbts.form.issue.api'
            - '@request'
            - '@doctrine.orm.entity_manager'
            - '@oro_entity.routing_helper'
        tags:
            - { name: oro_tag.tag_manager }

    #Link Issue
    oro_academic_sbts.form.type.issue_select:
            class: '%oro_academic_sbts.form.type.select_issue.class%'
            tags:
                - { name: form.type, alias: oro_academic_sbts_issue_select }

    oro_academic_sbts.form.autocomplete.issue.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - '%oro_academic_sbts.entity.issue.class%'
            - ["code", "summary"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: issues, acl_resource: oro_academic_sbts_issue_view }

    oro_academic_sbts.form.type.link_issue:
        class: '%oro_academic_sbts.form.type.link_issue.class%'
        tags:
            - { name: form.type, alias: oro_academic_sbts_link_issue }


    oro_academic_sbts.form.link_issue:
        class: '%symfony.form.class%'
        factory: ["@form.factory", createNamed]
        arguments:
            - oro_academic_sbts_link_issue_form
            - oro_academic_sbts_link_issue

    oro_academic_sbts.form.handler.link_issue:
        class: '%oro_academic_sbts.form.handler.link_issue.class%'
        scope: request
        arguments:
            - '@oro_academic_sbts.form.link_issue'
            - '@request'
            - '@doctrine.orm.entity_manager'