workflows:
    simple_bts_issue_workflow:
        transitions:
            create:
                step_to: open
                is_start: true
                transition_definition: open_definition
                label: 'Created'
            start_progress:
                step_to: in_progress
                transition_definition: start_progress_definition
                label: 'Start Progress'
            stop_progress:
                step_to: open
                transition_definition: stop_progress_definition
                label: 'Stop Progress'
            resolve:
                step_to: resolved
                transition_definition: resolve_definition
                label: 'Resolve Issue'
                form_options:
                    attribute_fields:
                        resolution:
                            options:
                                required: true
            reopen:
                step_to: reopened
                transition_definition: reopen_definition
                label: 'Reopen Issue'
            close:
                step_to: closed
                transition_definition: close_definition
                label: 'Close Issue'